version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    # คอมเม้นท์หรือลบบรรทัดที่ใช้ volumes นี้ออกถ้าไม่จำเป็น
    # volumes:
    #   - .:/app
    environment:
      - GO111MODULE=off
